server:
  port: 443
  ssl:
    enabled: true
    key-alias: ripple_ssl
    key-store: classpath:ripple-ssl.p12
    key-store-type: PKCS12
    key-password: 123456789
    key-store-password: 123456789


spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ripple-db?currentSchema=public
    username: user
    password: password
    name: ripple-db
    pool:
      max-size: 1000
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
      authentication-database: admin
      database: chat-db
      repositories:
        type: reactive
      uuid-representation: standard
  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672
  flyway:
    url: jdbc:postgresql://localhost:5432/ripple-db?currentSchema=public
    user: user
    password: password
    locations: classpath:db/migration
    enabled: true
logging:
  level:
    hibernate:
      SQL: DEBUG
ripple:
  bootstrap:
    delete-data-on-startup: false
  secret-key: cfe4d164f94f129845c43feaf49a205e97571d2dddbedd239ba80cec852ab4bf
  refresh-token-expiration-minutes: 525600
  access-token-expiration-minutes: 10080
  user-data-dir: user_data/users
  chat-data-dir: user_data/chats
  page-size:
    simple-posts: 12
    post-comments: 20
    comment-replies: 20
    followers-list: 30
  routes:
    auth:
      val: auth
      login: ${ripple.routes.auth.val}/login
      register: ${ripple.routes.auth.val}/register
      refresh-token: ${ripple.routes.auth.val}/refresh-token
